import MatchHeadingContent from "./MachingHeading";
import LocatingInformatonContent from "./LocatingInformation";
import trueFalseContent from "./TrueFalse";
import SummaryCompletionContent from "./SummaryCompletion";
import DiagramLablingContent from "./DiagramLabling";
import MatchingSentenceEndingsContent from "./MatchingSentenceEndings";
import MAtchingFeaturesContent from "./MatchingFeatures";
import SentenceCompletionContent from "./SentenceCompletion";
import ShortAnswerQueContent from "./ShortAnswerQue";
import FlowChartContent from "./FlowChartCompletion";
import NoteCompletionContent from "./NoteCompletion";
import YesNoContent from "./YesNo";
import TableCompletionContent from "./TableCompletion";
import MultipleChoiceQueContent from "./MultipleChoiceQue";
import MultipleCheckboxChoiceQueContent from "./MultipleCheckBoxQuestions";

export const MatchHeading = MatchHeadingContent;
export const LocatingInformation = LocatingInformatonContent;
export const TrueFalse = trueFalseContent;
export const SummarCompletion = SummaryCompletionContent;
export const DiagramLabling = DiagramLablingContent;
export const MatchingSentenceEndings = MatchingSentenceEndingsContent;
export const MatchingFeatures = MAtchingFeaturesContent;
export const SentenceCompletion = SentenceCompletionContent;
export const ShortAnswerQue = ShortAnswerQueContent;
export const FlowChartCompletion = FlowChartContent;
export const NoteCompletion = NoteCompletionContent;
export const YesNo = YesNoContent;
export const TableCompletion = TableCompletionContent;
export const MultipleChoiceQue = MultipleChoiceQueContent;
export const MultipleCheckboxChoiceQue = MultipleCheckboxChoiceQueContent;
